version: '3'
services:
  origin:
    image: quay.io/washpost/fusion-origin
    build: ./origin
    environment:
      NODE_ENV:
      HTTP_ENGINE: http://engine.fusion:8080
      HTTP_RESOLVER: http://resolver.fusion:8080
      LAMBDA_ENGINE:
      LAMBDA_RESOLVER:
      ON_DEMAND:
    links:
      - 'engine:engine.fusion'
      - 'resolver:resolver.fusion'
    ports:
      - '8080:8080'
      - '8081:8081'
    volumes:
      - '~/.aws:/home/nginx/.aws:ro'
      - './origin/src:/etc/nginx/src:ro'

  dao:
    image: quay.io/washpost/fusion-dao
    build: ./dao
    environment:
      NODE_ENV:
      DAO_CREDENTIALS: |
        localhost|abc|def
      MONGO_URLS: |
        localhost|mongodb://data:27017/${DB_NAME:-fusion_dev}
    links:
      - 'data'
    ports:
      - '8090:8080'
      - '8091:8081'
    volumes:
      - './dao/src:/etc/nginx/src:ro'

  engine:
    image: quay.io/washpost/fusion-engine
    build:
      context: .
      dockerfile: serverless.Dockerfile
      args:
        LAMBDA: engine
    environment:
      NODE_ENV:
      ENVIRONMENT: localhost
      DEBUG: fusion:*
      ON_DEMAND:
      CONTENT_BASE:
      DAO_URL: http://abc:def@localhost.dao.fusion:8080
    links:
      - 'dao:localhost.dao.fusion'
    ports:
      - '9001:8080'
    volumes:
      - '~/.aws:/root/.aws:ro'
      - './engine/bundle:/workdir/engine/bundle:ro'
      - './engine/src:/workdir/engine/src:ro'

  resolver:
    image: quay.io/washpost/fusion-resolver
    build:
      context: .
      dockerfile: serverless.Dockerfile
      args:
        LAMBDA: resolver
    environment:
      NODE_ENV:
      ENVIRONMENT: localhost
      HTTP_ENGINE: http://engine.fusion:8080
      LAMBDA_ENGINE:
    links:
      - 'engine:engine.fusion'
    ports:
      - '9002:8080'
    volumes:
      - './resolver/config:/workdir/resolver/config:ro'
      - './resolver/src:/workdir/resolver/src:ro'

  data:
    image: quay.io/washpost/mongo-localhost
    build:
      context: ./localhost/data
    ports:
      - '27017:27017'
    environment:
      WATCH: 'true'
    volumes:
      - 'fusion-data-volume:/data/db:rw'
      - './localhost/data/restore:/data/restore:rw'

volumes:
  fusion-data-volume: {}
