version: "2"
services:
  server:
    build:
      context: .
      dockerfile: multistage.Dockerfile
    image: fusion/server-prod
    command: start
    ports:
      - "80:8000"
    environment:
      NGINX_PORT: 8000
      NODEJS_PORT: 8080
      WORKERS: 0
      NODE_ENV: prod
