version: "3"
services:
  node:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "9229:9229"
    volumes:
      - "./client:/workdir/client"
      - "./layouts:/workdir/layouts"
      - "./templates:/workdir/templates"
      - "./server:/workdir/server"
