version: '3.4'

x-environment: &_environment
  DB_NAME: ${DB_NAME:-fusion_dev}
  MONGO_URL: mongodb://data:27017/${DB_NAME:-fusion_dev}
  PB_MONGODB_URI: mongodb://data:27017/${DB_NAME:-fusion_dev}

  HTTP_ENGINE: http://engine:8080
  HTTP_RESOLVER: http://resolver:8080
  LAMBDA_ENGINE:
  LAMBDA_RESOLVER:

  NODE_ENV:
  ENVIRONMENT: localhost
  CONTEXT_PATH:
  ON_DEMAND:
  DEBUG: fusion:*

networks:
  fusion:
    driver: bridge
    external: false
    internal: false

services:
  data:
    image: quay.io/washpost/mongo-localhost
    build: ./data
    environment:
      <<: *_environment
      WATCH: 'true'
    networks:
      fusion:
        aliases:
          - db
          - database
    ports:
      - '27017:27017'
    volumes:
      - './data/db:/data/db:rw'
      - './data/dumps:/data/dumps:rw'
      - './data/restore:/data/restore:rw'

  engine:
    image: quay.io/washpost/fusion-engine
    build:
      context: .
      dockerfile: serverless.Dockerfile
      args:
        LAMBDA: engine
    command: 'start:dev'
    depends_on:
      - data
    env_file:
      - .env
    environment:
      <<: *_environment
      CONTENT_BASE:
      MINIFY:
      # because we import ALL variables from .env, ignore PORT
      PORT: 8080
    networks:
      - fusion
    ports:
      - '9010:8080'
    volumes:
      - '${FUSION_REPO:-./bundle}:/workdir/engine/bundle:rw'
      - './engine/src:/workdir/engine/src:ro'
      - './dist:/workdir/engine/dist:rw'
      - './generated:/workdir/engine/generated:rw'

  resolver:
    image: quay.io/washpost/fusion-resolver
    build:
      context: .
      dockerfile: serverless.Dockerfile
      args:
        LAMBDA: resolver
    depends_on:
      - data
      - engine
    environment:
      <<: *_environment
      RESOLVE_FROM_DB: 'true' # should only be 'true' for local dev environments
      TRAILING_SLASH_RULE: # Options are FORCE, DROP, or NOOP
    networks:
      - fusion
    ports:
      - '9020:8080'
    volumes:
      - './resolver/config:/workdir/resolver/config:ro'
      - './resolver/src:/workdir/resolver/src:ro'

  origin:
    image: quay.io/washpost/fusion-origin
    build: ./origin
    depends_on:
      - engine
      - resolver
    environment:
      <<: *_environment
    networks:
      - fusion
    ports:
      - '80:8080'
      - '8081:8081'
    volumes:
      - './origin/src:/etc/nginx/src:ro'
      - './dist:/etc/nginx/dist:ro'
      - '${FUSION_REPO:-./bundle}/resources:/etc/nginx/resources:ro'
