version: "2"
services:
  entry-proxy:
    build: ./proxy
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
      - "10.65.0.2"
      - "10.67.0.2"
    environment:
      API_HANDLER: "proxy_pass http://engine-server:8080"
      DEFAULT_HANDLER: "proxy_pass http://resolver-server:8080"
      WATCH: "true"
    links:
      - "engine-server"
      - "resolver-server"
    ports:
      - "8080:8080"
    volumes:
      - "./proxy/src:/etc/nginx/src:ro"

  engine-server:
    build:
      context: .
      dockerfile: lambda-server/Dockerfile
      args:
        LAMBDA: engine
    environment:
      DEBUG: watcher:*
      WATCH: "true"
    ports:
      - "8081:8080"
    volumes:
      - "./engine/src:/workdir/lambda/src:ro"

  resolver-server:
    build:
      context: .
      dockerfile: lambda-server/Dockerfile
      args:
        LAMBDA: resolver
    environment:
      DEBUG: watcher:*
      WATCH: "true"
    ports:
      - "8082:8080"
    volumes:
      - "./resolver/src:/workdir/lambda/src:ro"
