version: '3'

networks:
  fusion:
    driver: bridge
    external: false
    internal: false

services:
  data:
    image: quay.io/washpost/mongo-localhost
    build: ./data
    environment:
      WATCH: 'true'
    networks:
      - fusion
    ports:
      - '27017:27017'
    volumes:
      - './data/db:/data/db:rw'
      - './data/restore:/data/restore:rw'

  dao:
    image: quay.io/washpost/fusion-dao
    build: ./dao
    depends_on:
      - data
    environment:
      NODE_ENV:
      DAO_CREDENTIALS: |
        localhost|abc|def
      MONGO_URLS: |
        localhost|mongodb://data:27017/${DB_NAME:-fusion_dev}
    networks:
      fusion:
        aliases:
          # the subdomain is used for multitenant determination
          - localhost.dao
    ports:
      - '8090:8080'
      - '8091:8081'
    volumes:
      - './dao/src:/etc/nginx/src:ro'

  engine:
    image: quay.io/washpost/fusion-engine
    build:
      context: .
      dockerfile: serverless.Dockerfile
      args:
        LAMBDA: engine
    depends_on:
      - dao
    environment:
      NODE_ENV:
      ENVIRONMENT: localhost
      DEBUG: fusion:*
      ON_DEMAND:
      CONTENT_BASE:
      CONTEXT_PATH:
      DAO_URL: http://abc:def@localhost.dao:8080
    networks:
      - fusion
    ports:
      - '9010:8080'
    volumes:
      # - '~/.aws:/root/.aws:ro'
      - '${FUSION_REPO:-./bundle}:/workdir/engine/bundle:rw'
      - './engine/src:/workdir/engine/src:ro'

  resolver:
    image: quay.io/washpost/fusion-resolver
    build:
      context: .
      dockerfile: serverless.Dockerfile
      args:
        LAMBDA: resolver
    depends_on:
      - dao
      - engine
    environment:
      NODE_ENV:
      ENVIRONMENT: localhost
      HTTP_ENGINE: http://engine:8080
      LAMBDA_ENGINE:
      DEBUG: fusion:*
      TRAILING_SLASH_RULE: # Options are FORCE, DROP, or NOOP
      DAO_URL: http://abc:def@localhost.dao:8080
      RESOLVE_FROM_DB: # should only be 'true' for local dev environments
    networks:
      - fusion
    ports:
      - '9020:8080'
    volumes:
      - './resolver/config:/workdir/resolver/config:ro'
      - './resolver/src:/workdir/resolver/src:ro'

  origin:
    image: quay.io/washpost/fusion-origin
    build: ./origin
    depends_on:
      - engine
      - resolver
    environment:
      NODE_ENV:
      HTTP_ENGINE: http://engine:8080
      HTTP_RESOLVER: http://resolver:8080
      LAMBDA_ENGINE:
      LAMBDA_RESOLVER:
      ON_DEMAND:
      CONTEXT_PATH:
    networks:
      - fusion
    ports:
      - '80:8080'
      - '8081:8081'
    volumes:
      # - '~/.aws:/home/nginx/.aws:ro'
      - './origin/src:/etc/nginx/src:ro'
