version: "2"
services:
  components:
    build: ./components
    volumes:
      - "fusion-components-volume:/fusion-components/export"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: start
    ports:
      - "80:8000"
    environment:
      NGINX_PORT: 8000
      NODEJS_PORT: 8080
      WORKERS: 0
    volumes:
      - "fusion-components-volume:/fusion/components"
volumes:
  fusion-components-volume: {}
