version: '2'
services:
  origin:
    build: ./origin
    environment:
      PORT: '8080'
      NODEJS_PORT: '8081'
      NODE_ENV:
      HTTP_ENGINE: http://engine:8082
      HTTP_RESOLVER: http://resolver:8083
      LAMBDA_ENGINE:
      LAMBDA_RESOLVER:
      ON_DEMAND:
    image: fusion-origin
    links:
      - 'engine'
      - 'resolver'
    ports:
      - "8080-8081:8080-8081"
    volumes:
      - '~/.aws:/home/nginx/.aws:ro'
      - './origin/src:/etc/nginx/src:ro'

  engine:
    build:
      context: .
      dockerfile: serverless.Dockerfile
      args:
        LAMBDA: engine
    environment:
      NODE_ENV:
      PORT: '8082'
      DEBUG: fusion:*
      ON_DEMAND:
      CONTENT_BASE:
      MONGO_URL:
    image: fusion-engine
    ports:
      - '8082:8082'
    volumes:
      - './engine/bundle:/workdir/engine/bundle:ro'
      - './engine/src:/workdir/engine/src:ro'

  resolver:
    build:
      context: .
      dockerfile: serverless.Dockerfile
      args:
        LAMBDA: resolver
    environment:
      PORT: '8083'
      NODE_ENV:
      HTTP_ENGINE: http://engine:8082
      LAMBDA_ENGINE:
    image: fusion-resolver
    links:
      - 'engine'
    ports:
      - '8083:8083'
    volumes:
      - './resolver/config:/workdir/resolver/config:ro'
      - './resolver/src:/workdir/resolver/src:ro'
