version: '3'

networks:
  fusion:
    driver: bridge
    external: false
    internal: false

services:
  data:
    image: quay.io/washpost/mongo-localhost
    build: ./data
    environment:
      WATCH: 'true'
    networks:
      fusion:
        aliases:
          - db
          - database
    ports:
      - '27017:27017'
    volumes:
      - './data/db:/data/db:rw'
      - './data/restore:/data/restore:rw'

  engine:
    image: quay.io/washpost/fusion-engine
    build:
      context: .
      dockerfile: serverless.Dockerfile
      args:
        LAMBDA: engine
    depends_on:
      - data
    environment:
      NODE_ENV:
      DEBUG: fusion:*
      ENVIRONMENT: localhost
      MONGO_URL: mongodb://data:27017/${DB_NAME:-fusion_dev}
      CONTENT_BASE:
      CONTEXT_PATH:
      MINIFY:
      ON_DEMAND:
    networks:
      - fusion
    ports:
      - '9010:8080'
    volumes:
      # - '~/.aws:/root/.aws:ro'
      - '${FUSION_REPO:-./bundle}:/workdir/engine/bundle:rw'
      - './engine/src:/workdir/engine/src:ro'
      - './dist:/workdir/engine/dist:rw'

  resolver:
    image: quay.io/washpost/fusion-resolver
    build:
      context: .
      dockerfile: serverless.Dockerfile
      args:
        LAMBDA: resolver
    depends_on:
      - data
      - engine
    environment:
      NODE_ENV:
      DEBUG: fusion:*
      ENVIRONMENT: localhost
      HTTP_ENGINE: http://engine:8080
      MONGO_URL: mongodb://data:27017/${DB_NAME:-fusion_dev}
      RESOLVE_FROM_DB: 'true' # should only be 'true' for local dev environments
      LAMBDA_ENGINE:
      TRAILING_SLASH_RULE: # Options are FORCE, DROP, or NOOP
    networks:
      - fusion
    ports:
      - '9020:8080'
    volumes:
      - './resolver/config:/workdir/resolver/config:ro'
      - './resolver/src:/workdir/resolver/src:ro'

  origin:
    image: quay.io/washpost/fusion-origin
    build: ./origin
    depends_on:
      - engine
      - resolver
    environment:
      NODE_ENV:
      HTTP_ENGINE: http://engine:8080
      HTTP_RESOLVER: http://resolver:8080
      LAMBDA_ENGINE:
      LAMBDA_RESOLVER:
      CONTEXT_PATH:
      ON_DEMAND:
    networks:
      - fusion
    ports:
      - '80:8080'
      - '8081:8081'
    volumes:
      # - '~/.aws:/home/nginx/.aws:ro'
      - './origin/src:/etc/nginx/src:ro'
      - './dist:/etc/nginx/dist:ro'
      - '${FUSION_REPO:-./bundle}/resources:/etc/nginx/resources:ro'
