version: '2'
services:
  entry-proxy:
    build: ./proxy
    environment:
      PORT: '8080'
      NODEJS_PORT: '8081'
      WATCH: 'true'
      ENGINE_HANDLER: http://engine-server:8082
      ENGINE_LAMBDA:
      RESOLVER_HANDLER: http://resolver-server:8083
      RESOLVER_LAMBDA:
    image: fusion-proxy
    links:
      - 'engine-server'
      - 'resolver-server'
    ports:
      - "8080-8081:8080-8081"
    volumes:
      - '~/.aws:/home/nginx/.aws:ro'
      - './proxy/src:/etc/nginx/src:ro'

  engine-server:
    build:
      context: .
      dockerfile: serverless.Dockerfile
      args:
        LAMBDA: engine
    environment:
      PORT: '8082'
      DEBUG: watcher:*,fusion:*
      WATCH: 'true'
      CONTENT_BASE:
      MONGO_URL:
    image: fusion-engine
    ports:
      - '8082:8082'
    volumes:
      - './engine/bundle:/workdir/engine/bundle:ro'
      - './engine/src:/workdir/engine/src:ro'

  resolver-server:
    build:
      context: .
      dockerfile: serverless.Dockerfile
      args:
        LAMBDA: resolver
    environment:
      PORT: '8083'
      DEBUG: watcher:*
      WATCH: 'true'
    image: fusion-resolver
    ports:
      - '8083:8083'
    volumes:
      - './resolver/config:/workdir/resolver/config:ro'
      - './resolver/src:/workdir/resolver/src:ro'
