version: "3"
services:
  renderer:
    build:
      dockerfile: dev.Dockerfile
    image: fusion/renderer-dev
    ports:
      - "9229:9229"
    volumes:
      - "./client:/workdir/client"
      - "./components:/workdir/components"
      - "./layouts:/workdir/layouts"
      - "./proxy/cache:/workdir/proxy/cache"
      - "./resources:/workdir/resources"
      - "./server:/workdir/server"
      - "./templates:/workdir/templates"
    environment:
      NODE_ENV: development
