version: "3"
services:
  proxy:
    volumes:
      - "./proxy/conf.d:/proxy/conf.d:ro"
      - "./proxy/tmp:/proxy/tmp:rw"
    environment:
      WATCH: "true"

  renderer:
    build:
      context: ./renderer
      dockerfile: dev.Dockerfile
    image: fusion/renderer-dev
    ports:
      - "9229:9229"
    volumes:
      - "./renderer/client:/renderer/client:ro"
      - "./renderer/components:/renderer/components:ro"
      - "./renderer/layouts:/renderer/layouts:ro"
      - "./renderer/resources:/renderer/resources:ro"
      - "./renderer/server:/renderer/server:ro"
      - "./renderer/templates:/renderer/templates:ro"
    environment:
      NODE_ENV: development
