version: "2"
services:
  entry-proxy:
    build: ./proxy
    env_file:
      - ./.env
    environment:
      PORT: '8080'
      WATCH: "true"
    image: fusion-proxy
    links:
      - "engine-server"
      - "resolver-server"
    ports:
      - "8080:8080"
    volumes:
      - "~/.aws:/home/nginx/.aws:ro"
      - "./proxy/src:/etc/nginx/src:ro"

  engine-server:
    build:
      context: .
      dockerfile: serverless.Dockerfile
      args:
        LAMBDA: engine
    environment:
      PORT: '8080'
      DEBUG: watcher:*,fusion:*
      WATCH: "true"
      CONTENT_BASE:
      MONGO_URL:
    image: fusion-engine
    ports:
      - "8081:8080"
    volumes:
      - "${BUNDLE_DIR}:/workdir/engine/bundle:ro"
      - "./engine/src:/workdir/src:ro"

  resolver-server:
    build:
      context: .
      dockerfile: serverless.Dockerfile
      args:
        LAMBDA: resolver
    environment:
      PORT: '8080'
      DEBUG: watcher:*
      WATCH: "true"
    image: fusion-resolver
    ports:
      - "8082:8080"
    volumes:
      - "./resolver/src:/workdir/src:ro"
