version: "3"
services:
  renderer:
    build:
      context: .
      dockerfile: prod.Dockerfile
    image: fusion/renderer-prod
    ports:
      - "80:8080"
    environment:
      NODE_ENV: production
