version: "2"
services:
  engine-server:
    environment:
      CONTENT_BASE: 'https://${API_USERNAME}:${API_PASSWORD}@api.${ARC_ORG_NAME}.arcpublishing.com'
    volumes:
      - "${ASSET_DIR}:/workdir/assets:ro"
