# serverless.yml

service: fusion-engine

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage}
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-59fef325
    subnetIds:
      - subnet-ea737fb2
      - subnet-c3ece0e9
      - subnet-ee718da7
  environment:
    NODE_ENV: ${env:NODE_ENV, 'production'}
    ENVIRONMENT: ${self:provider.stage}
    ON_DEMAND: ${env:ON_DEMAND, 'true'}

functions:
  engine:
    handler: src/index.serverless
    # we don't want to include http events in production, as that will create API Gateway routes
    # but, we do need http events in offline development
    events: ${file(./events.${self:provider.stage}.yml):events}

package:
  exclude:
    - bundle/components/**/*
    - package.json
    - package-lock.json
    - src/rendering.json
    - serverless.yml
    - webpack.components.js

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: '0.0.0.0'
    port: ${env:PORT, '8080'}
    dontPrintOutput: true
