version: "2"

networks:
  fusion-cache:
    driver: bridge
    external: false
    internal: false

services:
  cache-proxy:
    build: .
    networks:
      - fusion-cache
    ports:
      - '80:8080'
      - '8081:8081'
    environment:
      LOCALHOST_CREDENTIAL: abc123
    volumes:
      - './src:/etc/nginx/src:ro'