# serverless.yml

service: fusion-resolver

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  engine:
    handler: src/app.serverless
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: '0.0.0.0'
    port: 8080
