# serverless.yml

service: fusion-resolver

provider:
  name: aws
  runtime: nodejs6.10
  stage: staging
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-59fef325
    subnetIds:
      - subnet-ea737fb2
      - subnet-c3ece0e9
      - subnet-ee718da7

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}

functions:
  resolver:
    handler: src/index.serverless
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

package:
  exclude:
    - package.json
    - package-lock.json
    - serverless.yml

plugins:
  - serverless-domain-manager
  - serverless-offline

custom:
  customDomain:
    domainName: 'fusion.staging.arcpublishing.com'
    stage: ${self:provider.stage}
    basePath: resolve
    createRoute53Record: true

  serverless-offline:
    host: '0.0.0.0'
    port: ${env:PORT, '8080'}
