# serverless.yml

service: fusion-resolver

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage}
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-59fef325
    subnetIds:
      - subnet-ea737fb2
      - subnet-c3ece0e9
      - subnet-ee718da7
  environment:
    NODE_ENV: ${env:NODE_ENV, 'production'}
    ENVIRONMENT: ${self:provider.stage}

functions:
  resolver:
    handler: src/index.serverless
    events: ${file(./events.${opt:stage}.yml):events}

package:
  exclude:
    - package.json
    - package-lock.json
    - serverless.yml

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: '0.0.0.0'
    port: ${env:PORT, '8080'}
