version: '2'
services:
  origin:
    image: quay.io/washpost/fusion-origin
    environment:
      NODE_ENV:
      ENVIRONMENT: localhost
      HTTP_ENGINE: http://engine.fusion:8080
      HTTP_RESOLVER: http://resolver.fusion:8080
      ON_DEMAND:
    links:
      - 'engine:engine.fusion'
      - 'resolver:resolver.fusion'
    ports:
      - '8080:8080'
      - '8081:8081'
    volumes:
      - '~/.aws:/home/nginx/.aws:ro'

  dao:
    image: quay.io/washpost/fusion-dao
    environment:
      NODE_ENV:
      ENVIRONMENT: localhost
      LOCALHOST_CREDENTIALS: abc:def
      LOCALHOST_MONGOURL: mongodb://data:27017/fusion_dev
    links:
      - 'data'
    ports:
      - '8090:8080'
      - '8091:8081'

  engine:
    image: quay.io/washpost/fusion-engine
    environment:
      NODE_ENV:
      ENVIRONMENT: localhost
      DEBUG: fusion:*
      ON_DEMAND:
      CONTENT_BASE:
      DAO_URL: http://abc:def@localhost.dao.fusion:8080
    links:
      - 'dao:localhost.dao.fusion'
    ports:
      - '9001:8080'
    volumes:
      - '~/.aws:/root/.aws:ro'
      - '${BUNDLE_DIR}:/workdir/engine/bundle:ro'

  resolver:
    image: quay.io/washpost/fusion-resolver
    environment:
      NODE_ENV:
      ENVIRONMENT: localhost
      HTTP_ENGINE: http://engine.fusion:8080
    links:
      - 'engine:engine.fusion'
    ports:
      - '9002:8080'
    volumes:
      - '${RESOLVER_DIR}:/workdir/resolver/config:ro'

  data:
    image: quay.io/washpost/mongo-localhost
    ports:
      - '27017:27017'
    environment:
      NODE_ENV:
      ENVIRONMENT: localhost
      WATCH: 'true'
    volumes:
      - 'fusion-data-volume:/data/db:rw'
      - './data/restore:/data/restore:rw'

volumes:
  fusion-data-volume: {}
