version: "2"
services:
  fusion:
    image: quay.io/washpost/fusion-localhost
    ports:
      - "8080-8083:8080-8083"
    environment:
      NODE_ENV: development
      HTTP_ENGINE: http://0.0.0.0:8082
      HTTP_RESOLVER: http://0.0.0.0:8083
      CONTENT_BASE:
      MONGO_URL:
    volumes:
      - '~/.aws:/home/nginx/.aws:ro'
      - '${BUNDLE_DIR}:/workdir/engine/bundle:ro'
      - '${RESOLVER_DIR}:/workdir/resolver/config:ro'
