version: "2"
services:
  data:
    build:
      context: ./data
    image: quay.io/washpost/mongo-localhost

  fusion:
    build:
      context: ..
      dockerfile: localhost/build.Dockerfile
    image: quay.io/washpost/fusion-localhost
