version: "2"
services:
  fusion:
    image: quay.io/washpost/fusion-localhost
    ports:
      # 8080 is the public origin proxy
      # 8081 is the private nodejs lambda proxy (provides a way for nginx to proxy to lambda)
      # 8082 is the rendering engine
      # 8083 is the resolver
      - "8080-8083:8080-8083"
    environment:
      NODE_ENV: development
      HTTP_ENGINE: http://0.0.0.0:8082
      HTTP_RESOLVER: http://0.0.0.0:8083
      MONGO_URL:
      CONTENT_BASE:
      LAMBDA_ENGINE:
      LAMBDA_RESOLVER:
      ON_DEMAND:
    volumes:
      - '~/.aws:/home/nginx/.aws:ro'
      - '${BUNDLE_DIR}:/workdir/engine/bundle:ro'
      - '${RESOLVER_DIR}:/workdir/resolver/config:ro'
